blueprint:
  name: ZHA - Aqara Smoke Detector (JY-GZ-01AQ) Automation
  description: >
    Automate ZHA-based Aqara smoke detectors (JY-GZ-01AQ).
    Designed for smoke alarm, cross-link alarms, manual test,
    buzzer control, and custom reactions.
  domain: automation
  source_url: https://github.com/yourrepo/zha-aqara-smoke-blueprint

  input:

    smoke_sensors:
      name: Smoke state entities (ZHA)
      selector:
        entity:
          domain: binary_sensor
          device_class: smoke
          multiple: true

    linkage_alarm:
      name: Linkage alarm entity (optional)
      selector:
        entity:
          domain: binary_sensor

    self_test_button:
      name: Self-test button
      selector:
        entity:
          domain: button

    buzzer_alarm:
      name: Buzzer manual alarm switch
      selector:
        entity:
          domain: switch

    buzzer_mute:
      name: Buzzer manual mute switch
      selector:
        entity:
          domain: switch

    enable_linkage:
      name: Linkage alarm enable switch
      selector:
        entity:
          domain: switch

    heartbeat_indicator:
      name: Heartbeat indicator switch
      selector:
        entity:
          domain: switch

    alarm_actions:
      name: Automation - On Smoke Alarm
      selector:
        action: {}

    linkage_actions:
      name: Automation - On Linkage Alarm
      selector:
        action: {}

    test_actions:
      name: Automation - On Self-Test
      selector:
        action: {}

    clear_actions:
      name: Automation - On Alarm Cleared
      selector:
        action: {}

mode: single
max_exceeded: silent

variables:
  smoke_sensors: !input smoke_sensors
  linkage_alarm: !input linkage_alarm
  self_test_button: !input self_test_button
  buzzer_alarm: !input buzzer_alarm
  buzzer_mute: !input buzzer_mute
  enable_linkage: !input enable_linkage
  heartbeat_indicator: !input heartbeat_indicator

trigger:

  # Smoke detected from ANY selected detector
  - platform: state
    entity_id: !input smoke_sensors
    from: "off"
    to: "on"
    id: smoke_alarm

  # Linkage alarm triggered
  - platform: state
    entity_id: !input linkage_alarm
    from: "off"
    to: "on"
    id: linkage_alarm

  # Self-test pressed — using zha_event (keeps it general)
  - platform: event
    event_type: zha_event
    event_data:
      device_id: >
        {{ device_id(self_test_button) }}
    id: self_test

  # Any alarm cleared
  - platform: state
    entity_id: !input smoke_sensors
    from: "on"
    to: "off"
    id: clear

action:
  - choose:
      - conditions:
          - condition: trigger
            id: smoke_alarm
        sequence: !input alarm_actions

      - conditions:
          - condition: trigger
            id: linkage_alarm
        sequence: !input linkage_actions

      - conditions:
          - condition: trigger
            id: self_test
        sequence: !input test_actions

      - conditions:
          - condition: trigger
            id: clear
        sequence: !input clear_actions

    default: []
